# Generated by Django 3.1.5 on 2021-03-30 03:40

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('accounts', '0007_siteuser_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='skills',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma separated list of skills.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
