# Generated by Django 3.1.5 on 2021-04-04 03:19

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210329_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
