# Generated by Django 3.1.5 on 2021-04-08 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_siteuser_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
