# Generated by Django 3.1.5 on 2021-04-08 22:38

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_siteuser_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='For US phone number include +1', max_length=128, null=True, region=None),
        ),
    ]
