# Generated by Django 3.1.5 on 2021-04-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210408_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='is_available',
            field=models.BooleanField(default=False, help_text='Open to new oppurtunities.'),
        ),
    ]
