# Generated by Django 3.1.5 on 2021-04-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_siteuser_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
