# Generated by Django 3.1.5 on 2021-04-12 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0010_auto_20200508_1851'),
        ('accounts', '0015_siteuser_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cities_light.city', verbose_name='city'),
        ),
    ]
