# Generated by Django 3.1.5 on 2021-04-20 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0016_auto_20210411_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
    ]
