# Generated by Django 3.1.5 on 2021-04-20 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0017_siteuser_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, to='auth.Permission'),
        ),
    ]
