# Generated by Django 3.1.5 on 2021-04-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20210403_2034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('name',), 'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='experience',
            name='headline',
            field=models.CharField(default='A star performer.', max_length=255),
            preserve_default=False,
        ),
    ]
