# Generated by Django 3.1.5 on 2021-04-08 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0010_auto_20200508_1851'),
        ('companies', '0003_auto_20210404_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.ForeignKey(default=2525, on_delete=django.db.models.deletion.PROTECT, to='cities_light.city', verbose_name='city'),
            preserve_default=False,
        ),
    ]
